### ISSUE TITLE
bot userの作成

### ISSUE THREAD

**Issue by Roadagain** [kosen13s/thunder-bot#3]

**Comment by Roadagain** [comment]
`@thunder` でユーザー作成した

**Comment by Roadagain** [comment]
- `channels:read`
- `channels:history`
- `chat:write:bot`
- `emoji:read`
- `bot`

のpermissionで追加完了

**Comment by Iruyan-Zak** [comment]
SlackにpostMessageできることを確認した

**Comment by Roadagain** [comment]
完了！
